/* WRECKMARCH — authoritative target acquisition and weapon firing owner */

const DEFAULT_HERO_PROFILE = Object.freeze({
  aimYOffset: 6,
  targetTurnRate: .22,
  moveTurnRate: .14,
  twinSpread2: .055,
  twinSpread3: .085,
  multiShotDamageScale: .9,
  projectile: Object.freeze({ lifeMs: 1180, scale: .74, radius: 8, offsetX: 2, offsetY: 2 })
});

export class WeaponSystem {
  constructor(scene, { projectileSystem }) { this.scene = scene; this.projectiles = projectileSystem; this.heroProfile = { ...DEFAULT_HERO_PROFILE, projectile: { ...DEFAULT_HERO_PROFILE.projectile } }; this.muzzleResolver = null; this.fireFeedback = null; }
  configureHero(profile = {}) { const projectile = profile.projectile ? { ...this.heroProfile.projectile, ...profile.projectile } : this.heroProfile.projectile; this.heroProfile = { ...this.heroProfile, ...profile, projectile }; if ('muzzleResolver' in profile) this.setMuzzleResolver(profile.muzzleResolver); if ('fireFeedback' in profile) this.setFireFeedback(profile.fireFeedback); return this; }
  setMuzzleResolver(resolver) { this.muzzleResolver = typeof resolver === 'function' ? resolver : null; return this; }
  setFireFeedback(handler) { this.fireFeedback = typeof handler === 'function' ? handler : null; return this; }
  acquireTarget(x, y, maxDistance = Infinity) { let best = null; let bestSq = maxDistance * maxDistance; this.scene.enemies.children.iterate(enemy => { if (!enemy?.active || enemy.hp <= 0) return; const dx = enemy.x - x; const dy = enemy.y - y; const distanceSq = dx * dx + dy * dy; if (distanceSq < bestSq) { best = enemy; bestSq = distanceSq; } }); return best; }
  getMuzzle(spread = 0) { if (this.muzzleResolver) return this.muzzleResolver(spread); const scene = this.scene; const angle = (scene.weaponAim || 0) + spread; const distance = scene.primaryWeapon?.muzzleDistance || 38; return new Phaser.Math.Vector2(scene.hero.x + Math.cos(angle) * distance, scene.hero.y + 6 + Math.sin(angle) * distance); }
  heroSpreads() { const mechanicalCount = this.scene.upgradeMechanicalState?.['twin-riveter']?.projectileCount; const count = Math.max(1, mechanicalCount || this.scene.twinShots || 1); if (count === 1) return [0]; if (count === 2) return [-this.heroProfile.twinSpread2, this.heroProfile.twinSpread2]; return [-this.heroProfile.twinSpread3, 0, this.heroProfile.twinSpread3]; }
  fireHeroProjectile(angle, damageScale = 1) { const scene = this.scene; const weapon = scene.primaryWeapon; if (!weapon) return null; const muzzle = this.getMuzzle(angle - scene.weaponAim); const p = this.heroProfile.projectile; const resolvedWeapon = scene.runStatState?.resolve?.()?.weapon || {}; const bullet = this.projectiles.spawn({ x: muzzle.x, y: muzzle.y, angle, speed: weapon.projectileSpeed, damage: weapon.damage * damageScale, pierceCount: Math.max(0, Math.floor(Number(resolvedWeapon.pierceCount ?? weapon.pierceCount) || 0)), ricochetCount: Math.max(0, Math.floor(Number(resolvedWeapon.ricochetCount ?? weapon.ricochetCount) || 0)), lifeMs: p.lifeMs, scale: p.scale, radius: p.radius, offsetX: p.offsetX, offsetY: p.offsetY }); return { bullet, muzzle }; }
  update(time) { const scene = this.scene; const weapon = scene.primaryWeapon; if (!scene.hero?.active || !weapon || scene.gameOver) return; const target = this.acquireTarget(scene.hero.x, scene.hero.y, weapon.range); if (target) { const desired = Phaser.Math.Angle.Between(scene.hero.x, scene.hero.y + this.heroProfile.aimYOffset, target.x, target.y); scene.weaponAim = Phaser.Math.Angle.RotateTo(scene.weaponAim || 0, desired, this.heroProfile.targetTurnRate); } else if (scene.move?.lengthSq?.() > .05) scene.weaponAim = Phaser.Math.Angle.RotateTo(scene.weaponAim || 0, Math.atan2(scene.move.y, scene.move.x), this.heroProfile.moveTurnRate); scene.updateWeaponPose?.(); const fireDelay = Number.isFinite(Number(scene.fireDelay)) ? Number(scene.fireDelay) : Number(weapon.fireDelay); if (!target || time < (scene.lastShot || 0) + fireDelay) return; scene.lastShot = time; const spreads = this.heroSpreads(); const shots = []; let flashPoint = null; spreads.forEach((spread, index) => { const shot = this.fireHeroProjectile(scene.weaponAim + spread, spreads.length > 1 ? this.heroProfile.multiShotDamageScale : 1); if (!shot) return; shots.push(shot); if (index === Math.floor(spreads.length / 2) || !flashPoint) flashPoint = shot.muzzle; }); if (!shots.length) return; this.fireFeedback?.({ scene, target, angle: scene.weaponAim, visualAngle: Number.isFinite(scene.visualAimAngle) ? scene.visualAimAngle : scene.weaponAim, muzzle: flashPoint, shots }); }
  fireSupportVolley({ originX, originY, angle, spreads = [0], muzzleDistance = 0, speed = 680, damage, lifeMs = 1100, scale = .66, tint = 0x66dce9, radius = 8, offsetX = 2, offsetY = 2, onShot = null }) { const shots = []; spreads.forEach(spread => { const shotAngle = angle + spread; const x = originX + Math.cos(shotAngle) * muzzleDistance; const y = originY + Math.sin(shotAngle) * muzzleDistance; const bullet = this.projectiles.spawn({ x, y, angle: shotAngle, speed, damage, lifeMs, scale, tint, radius, offsetX, offsetY }); const shot = { bullet, x, y, angle: shotAngle }; shots.push(shot); onShot?.(shot); }); return shots; }
}
