/* WRECKMARCH F0 — stable playable-character boundary */
import { getCharacterDefinition } from './character-registry.js?v=5';
import { createRunStatState, mirrorResolvedRunStats } from '../stats/run-stat-state.js?v=4';
import { createWeaponRuntimeState, resolveCharacterSignatureWeapon } from '../combat/weapon-registry.js?v=2';

export class CharacterSystem {
  constructor(scene, characterId = 'runner', { productionValidationDefinition = null } = {}) { this.scene = scene; this._resetHealthOnNextInstall=Boolean(scene?.hero); if (productionValidationDefinition) { if (productionValidationDefinition.id !== characterId) throw Error(`Production validation character mismatch: ${productionValidationDefinition.id} != ${characterId}`); this._bindDefinition(productionValidationDefinition); } else this.select(characterId); }
  _bindDefinition(definition) { const previousCharacterId=this.characterId??this.scene.characterSystem?.characterId??null; const weaponDefinition=resolveCharacterSignatureWeapon(definition); this.characterId=definition.id; this.definition=definition; this.weaponDefinition=weaponDefinition; this.scene.characterId=definition.id; this.scene.characterDefinition=definition; this.scene.startingWeaponId=weaponDefinition.id; this.scene.activeWeaponId=weaponDefinition.id; this.scene.weaponDefinition=weaponDefinition; if(previousCharacterId&&previousCharacterId!==definition.id)this._resetHealthOnNextInstall=true; return definition; }
  select(characterId) { return this._bindDefinition(getCharacterDefinition(characterId)); }
  applyGameplayDefaults({ resetHealth=false }={}) { const {scene,definition,weaponDefinition}=this; const characterBase={...definition.stats,...definition.combatProfile}; const weaponBase={...weaponDefinition.stats}; const runtimeWeapon=createWeaponRuntimeState(weaponDefinition); scene.primaryWeapon={...runtimeWeapon,...(scene.primaryWeapon?.id===weaponDefinition.id?scene.primaryWeapon:{}),id:weaponDefinition.id}; scene.startingWeaponId=weaponDefinition.id; scene.activeWeaponId=weaponDefinition.id; scene.weaponDefinition=weaponDefinition; const runStats=createRunStatState({characterBase,weaponBase}); scene.runStatState=runStats; mirrorResolvedRunStats(scene,runStats.resolve()); scene.playerPassive=definition.passive||null; scene.playerCombatProfile=definition.combat||scene.playerCombatProfile; if(definition.combat?.invulnerabilityMs!=null)scene.heroInvulnMs=definition.combat.invulnerabilityMs; if(resetHealth||!Number.isFinite(scene.heroHp))scene.heroHp=definition.stats.maxHp; if(scene.hero?.body?.setCircle){const p=definition.physics;scene.hero.body.setCircle(p.radius,p.offsetX,p.offsetY)} return definition; }
  createHero(x,y){const {scene,definition}=this,bootstrap=definition.bootstrap;scene.heroShadow=scene.add.ellipse(x,y+38,52,17,0x000000,.28).setDepth(20);scene.hero=scene.physics.add.sprite(x,y,bootstrap.texture).setDepth(bootstrap.depth).setScale(bootstrap.scale);scene.hero.play(bootstrap.animation);scene.hero.setCollideWorldBounds(true);this.applyGameplayDefaults({resetHealth:true});scene.heroKnockback=new Phaser.Math.Vector2();scene.move=new Phaser.Math.Vector2();return scene.hero;}
  installProductionVisuals(){const {scene,definition}=this,{idle,run}=definition.animations;for(const animation of [idle,run]){if(scene.anims.exists(animation.key))scene.anims.remove(animation.key);scene.anims.create({key:animation.key,frames:animation.frames.map(key=>({key})),frameRate:animation.frameRate,repeat:-1})}const render=definition.render;scene.hero.stop().setTexture(render.idleTexture).setOrigin(render.originX,render.originY).setScale(render.scale).setFlipX(false).play(idle.key,true);const resetHealth=this._resetHealthOnNextInstall===true;this.applyGameplayDefaults({resetHealth});this._resetHealthOnNextInstall=false;scene.__characterSystemReady=true;scene.__hunterProductionVisual=true;return definition;}
  updateLocomotionVisuals(){const {scene,definition}=this,hero=scene.hero;if(!hero||!scene.move)return;const motion=definition.locomotion,moving=scene.move.lengthSq()>motion.movingThresholdSq,key=moving?definition.animations.run.key:definition.animations.idle.key;if(hero.anims.currentAnim?.key!==key)hero.play(key,true);if(moving){const movePower=Phaser.Math.Clamp(scene.move.length(),0,1),speedRatio=(scene.heroSpeed||definition.stats.moveSpeed)/motion.animationBaseSpeed;hero.anims.timeScale=Phaser.Math.Clamp(speedRatio*Phaser.Math.Linear(motion.minTimeScale,motion.maxTimeScale,movePower),motion.minTimeScale,motion.maxTimeScale);hero.setFlipX(scene.move.x < -motion.flipThreshold);hero.setRotation(Phaser.Math.Linear(hero.rotation||0,Phaser.Math.Clamp(scene.move.x,-1,1)*motion.leanRadians,motion.leanLerp));}else hero.setRotation(Phaser.Math.Linear(hero.rotation||0,0,motion.settleLerp));}
  getWeaponSocket(aimIndex){const weapon=this.definition.weapon,leftFacing=aimIndex>=weapon.leftFacingMinIndex&&aimIndex<=weapon.leftFacingMaxIndex;return{x:this.scene.hero.x+(leftFacing?-weapon.socketOffsetX:weapon.socketOffsetX),y:this.scene.hero.y+weapon.socketOffsetY};}
  getMuzzleReach(aimIndex){const weapon=this.definition.weapon;return aimIndex%2?weapon.muzzleReachDiagonal:weapon.muzzleReachStraight;}
}
