/* WRECKMARCH — production art override (non-invasive) */
import { ART_SVG } from './assets/art-pack.js?v=2';
import { installScrapRatVisuals } from './enemies/scrap-rat-visuals.js?v=5';
const wait = ms => new Promise(r => setTimeout(r, ms));
async function getScene(){const start=performance.now();while(performance.now()-start<9000){const game=window.__WM_GAME__||window.Phaser?.GAMES?.find(Boolean)||window.Phaser?.GAMES?.[0];const s=game?.scene?.getScene?.('Wreckmarch');if(s?.sys?.isActive?.()&&s.hero&&s.cart)return s;await wait(50)}throw new Error('Art override timed out waiting for scene')}
function svgUrl(svg){return URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}))}
async function loadSvgPack(scene){const entries=Object.entries(ART_SVG);for(const [key,svg] of entries){const url=svgUrl(svg);scene.load.image(key,url);scene.load.once(`filecomplete-image-${key}`,()=>URL.revokeObjectURL(url))}return new Promise((resolve,reject)=>{scene.load.once('complete',resolve);scene.load.once('loaderror',f=>reject(new Error(`Art asset failed: ${f?.key||'unknown'}`)));scene.load.start()})}
function rebuildAnimations(scene){for(const key of ['hero-run','hero-idle'])if(scene.anims.exists(key))scene.anims.remove(key);scene.anims.create({key:'hero-run',frames:[{key:'art-runner-a'},{key:'art-runner-b'}],frameRate:9,repeat:-1});scene.anims.create({key:'hero-idle',frames:[{key:'art-runner-a'},{key:'art-runner-b'}],frameRate:2,repeat:-1})}
function applyHero(scene){scene.hero.setTexture('art-runner-a').setScale(.92);scene.hero.body.setCircle(22);scene.hero.body.setOffset(26,24);const shadow=scene.heroShadow;shadow.setScale(1.04,.9);const originalMove=scene.updateMovement.bind(scene);scene.updateMovement=function(time){originalMove(time);const moving=this.move.lengthSq()>.05;this.heroShadow.setPosition(this.hero.x,this.hero.y+50).setScale(moving?1.12:1.04,moving?.82:.9)}}
function applyFortress(scene){scene.cart.setScale(.82);scene.cartBody.setTexture('art-fortress-body').setPosition(0,0);[[-58,41],[-20,42],[22,42],[59,41]].forEach((p,i)=>scene.cartWheels[i].setTexture('art-wheel').setPosition(...p).setScale(1));scene.turrets.forEach((turret,i)=>{turret.setTexture('art-turret').setOrigin(.28,.55).setScale(.88);if(!i)turret.setPosition(18,-30)});scene.cartShadow.setPosition(0,38).setScale(1.35,1.15);scene.cartCore.setCircle(42);scene.cartCore.body.setOffset(-4,-4);scene.addTurret=function(x,y){const turret=this.add.image(x,y,'art-turret').setOrigin(.28,.55).setScale(.88);this.cart.add(turret);this.turrets.push(turret);this.weaponLevel=this.turrets.length;this.cameras?.main?.flash(90,240,180,88,false);this.playTone?.(310,.045,'square',.025)};scene.updateFortress=function(dt,time){const desiredX=Phaser.Math.Clamp(this.hero.x-this.move.x*92,74,466);const desiredY=Phaser.Math.Clamp(this.hero.y-this.move.y*86-92,150,740);const follow=1-Math.pow(.001,dt);this.cart.x=Phaser.Math.Linear(this.cart.x,desiredX,follow*.27);this.cart.y=Phaser.Math.Linear(this.cart.y,desiredY,follow*.27);this.cart.rotation=Phaser.Math.Linear(this.cart.rotation,this.move.x*.025,.08);const rolling=Phaser.Math.Clamp(this.move.length(),0,1);this.cartWheels.forEach((w,i)=>w.rotation+=.055+rolling*.12*(i%2?1:.95));this.cartBody.y=Math.sin(time*.012)*(1+rolling*1.2);this.cartCore.setPosition(this.cart.x,this.cart.y);this.cartCore.body.updateFromGameObject();if(time>this.lastSmokeAt+(rolling?180:420)){this.lastSmokeAt=time;this.spawnSmoke(this.cart.x+47,this.cart.y-34);if(rolling)this.spawnDust(this.cart.x-42,this.cart.y+40,.95)}const target=this.weaponSystem?.acquireTarget?.(this.cart.x,this.cart.y,430)||null;if(target){const angle=Phaser.Math.Angle.Between(this.cart.x,this.cart.y-18,target.x,target.y);this.turrets.forEach(t=>t.rotation=Phaser.Math.Angle.RotateTo(t.rotation,angle-this.cart.rotation,.14))}}}
function enrichWorld(scene){const texture=scene.add.tileSprite(270,510,540,900,'art-wasteland').setDepth(1).setAlpha(.24).setTint(0xe8c49a);texture.setBlendMode(Phaser.BlendModes.MULTIPLY);[[88,190,'art-scrap-pile',.62,.08],[448,262,'art-barrel',.62,-.12],[92,504,'art-barrel',.5,.18],[445,602,'art-scrap-pile',.6,-.08],[116,770,'art-scrap-pile',.54,.12],[424,825,'art-barrel',.48,-.16]].forEach(([x,y,key,s,r])=>scene.add.image(x,y,key).setDepth(2).setScale(s).setRotation(r).setAlpha(.68))}
export async function applyProductionArt(){const scene=await getScene();await loadSvgPack(scene);rebuildAnimations(scene);await installScrapRatVisuals(scene);applyHero(scene);applyFortress(scene);enrichWorld(scene);scene.cart.setPosition(scene.hero.x,Math.max(170,scene.hero.y-105));window.__WM_ART_V2__=true;document.documentElement.dataset.wreckmarchArt='v2';window.__WM_LOG__?.('Art pack v2 applied: Runner + production Scrap Rat + Fortress + wasteland');return true}
