import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const read = (path: string) => readFileSync(path, 'utf8');

describe('balance run report bridge contract', () => {
  it('keeps GitHub credentials out of the client and uses the OIDC workflow bridge', () => {
    const workflow = read('.github/workflows/balance-run-report-bridge.yml');
    const provider = read('src/telemetry/run-report-provider.js');
    const runtime = read('src/telemetry/telemetry-runtime.js');
    const html = read('index.html');
    const worker = read('infra/cloudflare/wreckmarch-run-reports/worker.js');
    const migration = read('infra/cloudflare/wreckmarch-run-reports/migrations/001_run_reports.sql');
    const hud = read('src/mobile-hud-polish.js');
    const hudLoader = read('src/mobile-hud-loader-telemetry-v1.js');
    const phaseD1 = read('src/phase-d1-runtime.js');
    const finalPolish = read('src/final-polish-runtime.js');
    const smokeScript = read('scripts/ci-smoke.mjs');

    expect(workflow).toContain('id-token: write');
    expect(workflow).toContain('issues: write');
    expect(workflow).toContain("core.getIDToken('wreckmarch-run-reports')");
    expect(workflow).toContain("cron: '*/5 * * * *'");
    expect(workflow).toContain('/bridge/pending');
    expect(workflow).toContain('/bridge/ack');
    expect(workflow).toContain('github.rest.issues.createComment');
    expect(workflow).toContain('report.issueComments');
    expect(provider).toContain("wmTelemetry') === '1'");
    expect(provider).not.toContain('GITHUB_TOKEN');
    expect(provider).toContain("mode: 'cors'");
    expect(provider).toContain("credentials: 'omit'");
    expect(provider).toContain('MAX_KEEPALIVE_BYTES');
    expect(provider).toContain('wreckmarch-telemetry-probe');
    expect(runtime).toContain("./run-report-provider.js?v=3");
    expect(runtime).toContain('const wrapper = function telemetryAwareEndRun');
    expect(runtime).toContain('scene.endRun = wrapper');
    expect(runtime).toContain('telemetry.finalize(reason)');
    expect(runtime).toContain('previousHook?.wrapper === scene.endRun');
    expect(runtime).toContain('installEndRunTelemetryHook(scene);');
    expect(runtime).toContain('game.__wreckmarchRunReportProvider');
    expect(runtime).toContain('telemetry.provider = transport.provider');
    expect(runtime).toContain('export async function sendCurrentRunReport');
    expect(runtime).toContain('sendReport: reason => sendCurrentRunReport(game, reason)');
    expect(runtime).toContain('await provider.submit(report)');
    expect(runtime).toContain("manualReportFailure('finalize'");
    expect(runtime).toContain("manualReportFailure('transport'");
    expect(html).toContain('./src/telemetry/telemetry-runtime.js?v=13');
    expect(html).toContain('./src/phase-d1-runtime.js?v=24');
    expect(html).not.toContain('./src/telemetry/telemetry-debug-ui.js');
    expect(html).toContain('./src/mobile-hud-loader-telemetry-v1.js');
    expect(hudLoader).toContain('./mobile-hud-polish.js?asset=telemetry-hud-20260831-213754');
    expect(html).toContain('./src/final-polish-runtime.js?v=2');
    expect(phaseD1).not.toContain('mobile-hud-polish');
    expect(finalPolish).not.toContain('mobile-hud-polish');
    expect(hud).toContain("'SEND REPORT'");
    expect(hud).toContain("window.__WM_TELEMETRY_RUNTIME__?.sendReport");
    expect(hud).toContain('FINALIZE → QUEUE → HTTP');
    expect(hud).toContain('__WM_LAST_MANUAL_REPORT_RESULT__');
    expect(hud).toContain("END_RUN_OWNER_VERSION='runtime-v5-test'");
    expect(hud).toContain('scene.__mobileHudEndRunOwnerVersion===END_RUN_OWNER_VERSION');
    expect(hud).toContain('wreckmarchEndRunLayout=END_RUN_OWNER_VERSION');
    expect(smokeScript).toContain('TELEMETRY_SMOKE');
    expect(smokeScript).toContain("endRunVersion !== 'runtime-v5-test'");
    expect(worker).toContain('INSERT OR IGNORE INTO run_reports');
    expect(worker).toContain("stage: 'd1_insert'");
    expect(worker).toContain('issueComments');
    expect(worker).not.toContain('ensureSchema');
    expect(worker).not.toContain('.exec(');
    expect(worker).not.toContain('.slice(0, 50000)');
    expect(migration).toContain('CREATE TABLE IF NOT EXISTS run_reports');
    expect(migration).toContain('CREATE INDEX IF NOT EXISTS idx_run_reports_status');
  });
});
