import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const read = (path: string) => readFileSync(path, 'utf8');

describe('balance run report bridge contract', () => {
  it('keeps GitHub credentials out of the client and uses the OIDC workflow bridge', () => {
    const workflow = read('.github/workflows/balance-run-report-bridge.yml');
    const pagesWorkflow = read('.github/workflows/pages.yml');
    const provider = read('src/telemetry/run-report-provider.js');
    const runtime = read('src/telemetry/telemetry-runtime.js');
    const html = read('index.html');
    const worker = read('infra/cloudflare/wreckmarch-run-reports/worker.js');
    const migration = read('infra/cloudflare/wreckmarch-run-reports/migrations/001_run_reports.sql');
    const hud = read('src/mobile-hud-polish.js');
    const hudLoader = read('src/mobile-hud-loader-canonical-v2.js');
    const phaseD1 = read('src/phase-d1-runtime.js');
    const finalPolish = read('src/final-polish-runtime.js');
    const resultsScreen = read('src/ui/results-screen.js');
    const smokeScript = read('scripts/ci-smoke.mjs');

    expect(workflow).toContain('id-token: write');
    expect(workflow).toContain('issues: write');
    expect(workflow).toContain("core.getIDToken('wreckmarch-run-reports')");
    expect(workflow).toContain("cron: '2,7,12,17,22,27,32,37,42,47,52,57 * * * *'");
    expect(workflow).toContain('/bridge/pending');
    expect(workflow).toContain('/bridge/ack');
    expect(workflow).toContain('const MAX_BRIDGE_PASSES = 20');
    expect(workflow).toContain('for (let pass = 1; pass <= MAX_BRIDGE_PASSES; pass += 1)');
    expect(workflow).toContain('if (reports.length === 0) break');
    expect(workflow).toContain('if (passFailures > 0) break');
    expect(workflow).toContain('Submitted Wreckmarch run reports this bridge run');
    expect(workflow).not.toContain('paths:');
    expect(workflow).toContain('github.rest.issues.createComment');
    expect(workflow).toContain('report.issueComments');
    expect(provider).toContain("wmTelemetry') === '1'");
    expect(provider).not.toContain('GITHUB_TOKEN');
    expect(provider).toContain("mode: 'cors'");
    expect(provider).toContain("credentials: 'omit'");
    expect(provider).toContain('MAX_KEEPALIVE_BYTES');
    expect(provider).toContain('wreckmarch-telemetry-probe');
    expect(runtime).toContain("./run-report-provider.js?v=3");
    expect(runtime).toContain("./run-telemetry.js?v=6");
    expect(runtime).toContain('const wrapper = function telemetryAwareEndRun');
    expect(runtime).toContain('scene.endRun = wrapper');
    expect(runtime).toContain('telemetry.finalize(reason)');
    expect(runtime).toContain('previousHook?.wrapper === scene.endRun');
    expect(runtime).toContain('installEndRunTelemetryHook(scene);');
    expect(runtime).toContain('game.__wreckmarchRunReportProvider');
    expect(runtime).toContain('telemetry.provider = transport.provider');
    expect(runtime).toContain('export async function sendCurrentRunReport');
    expect(runtime).toContain('sendReport: reason => sendCurrentRunReport(game, reason)');
    expect(runtime).toContain('await provider.submit(report)');
    expect(runtime).toContain("manualReportFailure('finalize'");
    expect(runtime).toContain("manualReportFailure('transport'");
    expect(html).toContain('./src/telemetry/telemetry-runtime.js?v=15');
    expect(html).toContain('./src/phase-d1-runtime.js?v=29&u5=3');
    expect(pagesWorkflow).toContain('src/phase-c1-runtime.js?v=19');
    expect(pagesWorkflow).toContain('src/phase-d1-runtime.js?v=29');
    expect(pagesWorkflow).toContain('src/characters/character-runtime-presentation.js?v=3&wrecker=4');
    expect(pagesWorkflow).toContain('src/characters/shotgun-production-presentation.js?v=3&wrecker=4');
    expect(pagesWorkflow).toContain('src/characters/shotgun-runtime-presentation.js?v=3');
    expect(pagesWorkflow).toContain('src/characters/shotgun-locomotion-art.js?v=2');
    expect(pagesWorkflow).toContain('src/characters/shotgun-baked-locomotion.js?v=1');
    expect(pagesWorkflow).toContain('SHOTGUN_BAKED_RUN_POSES');
    expect(pagesWorkflow).toContain('bakeShotgunRunTextures');
    expect(pagesWorkflow).toContain('src/characters/runner-production-presentation.js?v=1');
    expect(pagesWorkflow).toContain('src/phase-b-runtime.js?v=6');
    expect(pagesWorkflow).toContain('src/phase-c-runtime.js?v=24');
    expect(pagesWorkflow).toContain('src/characters/character-system.js?v=10');
    expect(pagesWorkflow).toContain('src/combat/weapon-registry.js?v=2');
    expect(pagesWorkflow).toContain('src/combat/definitions/rivet-gun.js?v=2');
    expect(pagesWorkflow).toContain('src/enemies/enemy-system.js?v=24');
    expect(pagesWorkflow).toContain('src/combat/weapon-system.js?v=8');
    expect(pagesWorkflow).toContain('src/upgrades/upgrade-scene.js?v=1');
    expect(pagesWorkflow).toContain('src/upgrades/upgrade-roll-service.js?v=2');
    expect(pagesWorkflow).toContain('projectileCount: 1');
    expect(pagesWorkflow).toContain('halfSpreadRadians: 0');
    expect(pagesWorkflow).toContain('volleyDamageMultiplier: 1');
    expect(pagesWorkflow).toContain('heroVolleyProfile()');
    expect(pagesWorkflow).toContain("weaponVolley:s.primaryWeapon?.fireProfile?.projectileCount===1");
    expect(pagesWorkflow).toContain("weaponIdentity:s.characterSystem?.weaponDefinition?.id==='rivet-gun'");
    expect(pagesWorkflow).not.toContain('src/phase-d1-runtime.js?v=23');
    expect(pagesWorkflow).toContain('src/upgrades/upgrade-offer-pool.js?v=1');
    expect(pagesWorkflow).toContain('"./upgrades/upgrade-scene.js?v=1" wm-live-phase-c1.js');
    expect(pagesWorkflow).toContain('"./upgrade-offer-pool.js?v=1" wm-live-upgrade-scene.js');
    expect(pagesWorkflow).toContain('"./upgrade-roll-service.js?v=2" wm-live-upgrade-scene.js');
    expect(pagesWorkflow).not.toContain('"./upgrades/upgrade-offer-pool.js?v=1" wm-live-phase-c1.js');
    expect(pagesWorkflow).toContain("class UpgradeSceneV4 extends Phaser.Scene");
    expect(pagesWorkflow).toContain("gameScene.__upgradeSceneOwner = 'src/upgrades/upgrade-scene.js'");
    expect(pagesWorkflow).toContain("offer('explosive-rivet', 'HERO'");
    expect(pagesWorkflow).toContain('upgrade-icon-explosive-rivet');
    expect(pagesWorkflow).toContain("offer('triple-riveter', 'EVOLUTION'");
    expect(pagesWorkflow).toContain('upgrade-icon-triple-riveter');
    expect(html).not.toContain('./src/telemetry/telemetry-debug-ui.js');
    expect(html).toContain('./src/mobile-hud-loader-canonical-v2.js?rev=3');
    expect(hudLoader).toContain('./mobile-hud-polish.js?asset=canonical-hud-20260903-responsive-v2&rev=3');
    expect(html).toContain('./src/final-polish-runtime.js?v=2');
    expect(phaseD1).not.toContain('mobile-hud-polish');
    expect(finalPolish).not.toContain('mobile-hud-polish');
    expect(resultsScreen).toContain("report.textContent = 'SEND REPORT'");
    expect(resultsScreen).toContain('wm-results-report-button');
    expect(hud).not.toContain('scene.endRun=');
    expect(hud).not.toContain('END_RUN_OWNER_VERSION');
    expect(hud).not.toContain('wreckmarchEndRunLayout');
    expect(hud).not.toContain('TEST UI v5');
    expect(smokeScript).toContain('TELEMETRY_SMOKE');
    expect(smokeScript).toContain("document.querySelector('.wm-results-screen')");
    expect(smokeScript).toContain("document.querySelector('.wm-results-report-button')");
    expect(smokeScript).toContain("before.shellScreen !== 'results'");
    expect(smokeScript).toContain("before.owner !== 'game-shell-results-v1'");
    expect(smokeScript).toContain("before.label !== 'SEND REPORT'");
    expect(smokeScript).toContain('reportButton.click()');
    expect(smokeScript).not.toContain('layout?.reportBtn');
    expect(worker).toContain('INSERT OR IGNORE INTO run_reports');
    expect(worker).toContain("stage: 'd1_insert'");
    expect(worker).toContain('issueComments');
    expect(worker).not.toContain('ensureSchema');
    expect(worker).not.toContain('.exec(');
    expect(worker).not.toContain('.slice(0, 50000)');
    expect(migration).toContain('CREATE TABLE IF NOT EXISTS run_reports');
    expect(migration).toContain('CREATE INDEX IF NOT EXISTS idx_run_reports_status');
  });
});
