import { describe, expect, it } from 'vitest';
import { CURRENT_PRODUCTION_WORLD, getActiveWorldSectors, getWorldSectorGrid } from '../../src/world/world-contract.js';
import { BOSS_CLEARINGS,R3_WORLD_DISTRICT_VALIDATION,WORLD_DISTRICT_LIST,WORLD_LANDMARKS,getDistrictForSector,getDistrictMetadataForSector } from '../../src/world/world-district-contract.js';
describe('R3 canonical district contract',()=>{
it('covers all 64 production sectors exactly once without changing R2 streaming',()=>{const grid=getWorldSectorGrid(CURRENT_PRODUCTION_WORLD),covered=new Set<string>();for(let row=0;row<grid.rows;row++)for(let column=0;column<grid.columns;column++){const key=`${column}:${row}`;expect(covered.has(key)).toBe(false);covered.add(key);expect(getDistrictForSector(column,row)).toBeTruthy()}expect(grid.columns).toBe(8);expect(grid.rows).toBe(8);expect(covered.size).toBe(64);expect(R3_WORLD_DISTRICT_VALIDATION.ok).toBe(true);expect(R3_WORLD_DISTRICT_VALIDATION.coveredSectorCount).toBe(64)});
it('keeps production start in Central Wreckroads and R2 active bound intact',()=>{expect(getDistrictForSector(4,4).id).toBe('central-wreckroads');expect(getActiveWorldSectors(4800,4800,CURRENT_PRODUCTION_WORLD)).toHaveLength(9)});
it('gives every district landmarks',()=>{expect(WORLD_DISTRICT_LIST).toHaveLength(7);expect(WORLD_LANDMARKS).toHaveLength(14);for(const district of WORLD_DISTRICT_LIST)expect(WORLD_LANDMARKS.some(x=>x.districtId===district.id)).toBe(true)});
it('defines five valid Boss-capable open clearings in different districts',()=>{expect(BOSS_CLEARINGS).toHaveLength(5);expect(new Set(BOSS_CLEARINGS.map(x=>x.districtId)).size).toBe(5);for(const x of BOSS_CLEARINGS){const[c,r]=x.sectorKey.split(':').map(Number);expect(getDistrictForSector(c,r).id).toBe(x.districtId);expect(x.bossCapable&&x.openGround).toBe(true);expect(x.width).toBeGreaterThanOrEqual(480);expect(x.height).toBeGreaterThanOrEqual(420)}});
it('returns active-sector metadata rather than full-map prop allocation',()=>{const metadata=getActiveWorldSectors(4800,4800,CURRENT_PRODUCTION_WORLD).map(getDistrictMetadataForSector);expect(metadata).toHaveLength(9);expect(metadata.flatMap(x=>x.landmarks).length).toBeLessThan(WORLD_LANDMARKS.length);expect(metadata.flatMap(x=>x.bossClearings).length).toBeLessThan(BOSS_CLEARINGS.length)})});
